### ISSUE TITLE
Conflicts

### ISSUE THREAD

**Issue by SolarAquarion** [fusion809/artwork-maia#1]
/usr/share/metainfo/org.kde.maia.desktop.appdata.xml exists in both 'maia-icon-theme' and 'maia-wallpaper'
/usr/share/metainfo/org.kde.maia.desktop.appdata.xml exists in both 'maia-icon-theme' and 'plasma5-themes-maia'
/usr/share/metainfo/org.kde.maia.desktop.appdata.xml exists in both 'maia-icon-theme' and 'sddm-maia-theme'
/usr/share/metainfo/org.kde.maia.desktop.appdata.xml exists in both 'maia-wallpaper' and 'plasma5-themes-maia'
/usr/share/metainfo/org.kde.maia.desktop.appdata.xml exists in both 'maia-wallpaper' and 'sddm-maia-theme'
/usr/share/metainfo/org.kde.maia.desktop.appdata.xml exists in both 'plasma5-themes-maia' and 'sddm-maia-theme'

**Comment by fusion809** [comment]
This is still in early development so it's not quite ready for production use.

**Comment by fusion809** [comment]
Besides that problem doesn't relate to this repo it relates to my AUR package. Please report your errors at the right place.

**Comment by SolarAquarion** [comment]
Sorry
